### ISSUE TITLE
Palindrome Checker (One-liner)

### ISSUE THREAD

**Issue by Yogeshkarma** [J-B-Mugundh/HacktoberFestProjectsDump#12]
directory containing some curated python programs, 
if yes, Kindly add under hacktoberfest

**Comment by J-B-Mugundh** [comment]
@Yogeshkarma Sure, Go ahead! Kindly star ⭐ the repository before doing so

**Comment by Yogeshkarma** [comment]
@J-B-Mugundh  already gave the ⭐
